var huiguAdInit = {
    imgUrl:{
        page1:[
            {containerId:"page1-logo",url:"00/logo.png"},
            {containerId:"page1-car",url:"00/car.png"},
            {containerId:"page1-hospital",url:"00/hospital.png"},
            {containerId:"page1-huiguTitle",url:"00/huiguTitle.png"},
            {containerId:"page1-serviceIntroduce",url:"00/serviceIntroduce.png"},
            {containerId:"page1-start",url:"00/start.png"},
            {containerId:"page1-tree",url:"00/tree.png"},
            {containerId:"page1-yun1",url:"00/yun1.png"},
            {containerId:"page1-yun2",url:"00/yun2.png"},
            {containerId:"page1-yun3",url:"00/yun3.png"},
            {containerId:"page1-yun4",url:"00/yun4.png"}
        ],
        page2:[
            {containerId:"page2-background",url:"01/background.png"},
            {containerId:"page2-desk",url:"01/desk.png"},
            {containerId:"page2-doctor1",url:"01/doctor1.png"},
            {containerId:"page2-doctor2",url:"01/doctor2.png"},
            {containerId:"page2-door-close",url:"01/door-close.png"},
            {containerId:"page2-door-open",url:"01/door-open.png"},
            {containerId:"page2-hand",url:"01/hand.png"},
            {containerId:"page2-msg",url:"01/msg.png"},
            {containerId:"page2-patient",url:"01/patient.png"},
            {containerId:"page2-patient2",url:"01/patient2.png"},
            {containerId:"page2-title",url:"01/title.png"}
        ],
        page3:[
            {containerId:"page3-background",url:"02/background.png"},
            {containerId:"page3-left-hand",url:"02/left-hand.png"},
            {containerId:"page3-order",url:"02/order.png"},
            {containerId:"page3-pointer",url:"02/pointer.png"},
            {containerId:"page3-right-hand",url:"02/right-hand.png"},
            {containerId:"page3-title",url:"02/title.png"},
            {containerId:"page3-button-black",url:"02/button-black.png"},
            {containerId:"page3-cardid",url:"02/cardid.png"},
            {containerId:"page3-cover",url:"02/cover.png"},
            {containerId:"page3-msg",url:"02/msg.png"},
            {containerId:"page3-name",url:"02/name.png"},
            {containerId:"page3-phone-background",url:"02/phone-background.png"},
            {containerId:"page3-phone-menu",url:"02/phone-menu.png"},
            {containerId:"page3-phone-number",url:"02/phone-number.png"},
            {containerId:"page3-select-case1",url:"02/select-case1.png"},
            {containerId:"page3-select-case2",url:"02/select-case2.png"},
            {containerId:"page3-time-space",url:"02/time-space.png"},
            {containerId:"page3-top-col",url:"02/top-col.png"},
            {containerId:"page3-year",url:"02/year.png"},
        ],
        page4:[
            {containerId:"page4-background-far",url:"03/background-far.png"},
            {containerId:"page4-background-near",url:"03/background-near.png"},
            {containerId:"page4-compute",url:"03/compute.png"},
            {containerId:"page4-desk",url:"03/desk.png"},
            {containerId:"page4-dialog",url:"03/dialog.png"},
            {containerId:"page4-hand",url:"03/hand.png"},
            {containerId:"page4-mouse1",url:"03/mouse1.png"},
            {containerId:"page4-mouse2",url:"03/mouse2.png"},
            {containerId:"page4-patient-msg",url:"03/patient-msg.png"},
            {containerId:"page4-service",url:"03/service.png"},
            {containerId:"page4-title",url:"03/title.png"},
            {containerId:"page4-yun1",url:"03/yun1.png"},
            {containerId:"page4-yun2",url:"03/yun2.png"}
        ],
        page5:[
            {containerId:"page5-background",url:"04/background.png"},
            {containerId:"page5-compute",url:"04/compute.png"},
            {containerId:"page5-doctor1",url:"04/doctor1.png"},
            {containerId:"page5-doctor2",url:"04/doctor2.png"},
            {containerId:"page5-doctor3",url:"04/doctor3.png"},
            {containerId:"page5-hand",url:"04/hand.png"},
            {containerId:"page5-keybord",url:"04/keybord.png"},
            {containerId:"page5-keybord-line",url:"04/keybord-line.png"},
            {containerId:"page5-msg1",url:"04/msg1.png"},
            {containerId:"page5-msg2",url:"04/msg2.png"},
            {containerId:"page5-screen-back",url:"04/screen-back.png"},
            {containerId:"page5-screen-border",url:"04/screen-border.png"},
            {containerId:"page5-search",url:"04/search.gif"},
            {containerId:"page5-title",url:"04/title.png"},

            {containerId:"page5-background5",url:"05/background.png"},
            {containerId:"page5-background-title",url:"05/background-title.png"},
            {containerId:"page5-disease-msg",url:"05/disease-msg.png"},
            {containerId:"page5-doctor",url:"05/doctor.png"},
            {containerId:"page5-expert1",url:"05/expert1.png"},
            {containerId:"page5-expert2",url:"05/expert2.png"},
            {containerId:"page5-expert3",url:"05/expert3.png"},
            {containerId:"page5-expert2-phone",url:"05/expert2-phone.png"},
            {containerId:"page5-hand5",url:"05/hand.png"},
            {containerId:"page5-image",url:"05/image.png"},
            {containerId:"page5-light",url:"05/light.png"},
            {containerId:"page5-progress-bar",url:"05/progress-bar.gif"},
            {containerId:"page5-shadow-back",url:"05/shadow-back.png"},
            {containerId:"page5-shadow-line",url:"05/shadow-line.png"},
            {containerId:"page5-title5",url:"05/title.png"}
        ],
        page6:[
            {containerId:"page6-background",url:"06/background.png"},
            {containerId:"page6-flag",url:"06/flag.png"},
            {containerId:"page6-left-hand",url:"06/left-hand.png"},
            {containerId:"page6-left-hand-pointer",url:"06/left-hand-pointer.png"},
            {containerId:"page6-order",url:"06/order.png"},
            {containerId:"page6-right-hand-click",url:"06/right-hand-click.png"},
            {containerId:"page6-right-hand-close",url:"06/right-hand-close.png"},
            {containerId:"page6-right-hand-open",url:"06/right-hand-open.png"},
            {containerId:"page6-screen-back",url:"06/screen-back.png"},
            {containerId:"page6-image",url:"06/image.png"},
            {containerId:"page6-progress-bar",url:"06/progress-bar.gif"},
            {containerId:"page6-title",url:"06/title.png"}
        ],
        page7:[
            {containerId:"page7-circle",url:"06-5/circle.png"},
            {containerId:"page7-line1",url:"06-5/line.png"},
            {containerId:"page7-line2",url:"06-5/line.png"},
            {containerId:"page7-line3",url:"06-5/line.png"},
            {containerId:"page7-line4",url:"06-5/line.png"},
            {containerId:"page7-line5",url:"06-5/line.png"},
            {containerId:"page7-service1-icon",url:"06-5/service1-icon.png"},
            {containerId:"page7-service1-name",url:"06-5/service1-name.png"},
            {containerId:"page7-service2-icon",url:"06-5/service2-icon.png"},
            {containerId:"page7-service2-name",url:"06-5/service2-name.png"},
            {containerId:"page7-service3-icon",url:"06-5/service3-icon.png"},
            {containerId:"page7-service3-name",url:"06-5/service3-name.png"},
            {containerId:"page7-service4-icon",url:"06-5/service4-icon.png"},
            {containerId:"page7-service4-name",url:"06-5/service4-name.png"},
            {containerId:"page7-service5-icon",url:"06-5/service5-icon.png"},
            {containerId:"page7-service5-name",url:"06-5/service5-name.png"},
            {containerId:"page7-service-title",url:"06-5/service-title.png"},
            {containerId:"page7-title-back",url:"06-5/title-back.png"}
        ],
        page8:[
            {containerId:"page8-airfly",url:"07/airfly.png"},
            {containerId:"page8-background",url:"07/background.png"},
            {containerId:"page8-car",url:"07/car.png"},
            {containerId:"page8-gonglu",url:"07/gonglu.png"},
            {containerId:"page8-mountain",url:"07/mountain.png"},

            {containerId:"page8-doctor1",url:"08/doctor1.png"},
            {containerId:"page8-background8",url:"08/background.png"},
            {containerId:"page8-doctor2",url:"08/doctor2.png"},
            {containerId:"page8-expert",url:"08/expert.png"},
            {containerId:"page8-hand",url:"08/hand.png"},
            {containerId:"page8-light",url:"08/light.png"},
            {containerId:"page8-opera-table",url:"08/opera-table.png"},
            {containerId:"page8-title",url:"08/title.png"}
        ],
        page9:[
            {containerId:"page9-circle",url:"08-5/circle.png"},
            {containerId:"page9-line1",url:"08-5/line.png"},
            {containerId:"page9-line2",url:"08-5/line.png"},
            {containerId:"page9-line3",url:"08-5/line.png"},
            {containerId:"page9-line4",url:"08-5/line.png"},
            {containerId:"page9-line5",url:"08-5/line.png"},
            {containerId:"page9-service1-icon",url:"08-5/service1-icon.png"},
            {containerId:"page9-service1-name",url:"08-5/service1-name.png"},
            {containerId:"page9-service2-icon",url:"08-5/service2-icon.png"},
            {containerId:"page9-service2-name",url:"08-5/service2-name.png"},
            {containerId:"page9-service3-icon",url:"08-5/service3-icon.png"},
            {containerId:"page9-service3-name",url:"08-5/service3-name.png"},
            {containerId:"page9-service4-icon",url:"08-5/service4-icon.png"},
            {containerId:"page9-service4-name",url:"08-5/service4-name.png"},
            {containerId:"page9-service5-icon",url:"08-5/service5-icon.png"},
            {containerId:"page9-service5-name",url:"08-5/service5-name.png"},
            {containerId:"page9-service-title",url:"08-5/service-title.png"},
            {containerId:"page9-title-back",url:"08-5/title-back.png"}
        ],
        page10:[
            {containerId:"page10-background",url:"09/background.png"},
            {containerId:"page10-dialog",url:"09/dialog.png"},
            {containerId:"page10-left-hand",url:"09/left-hand.png"},
            {containerId:"page10-left-hand-pointer",url:"09/left-hand-pointer.png"},
            {containerId:"page10-mouse1",url:"09/mouse1.png"},
            {containerId:"page10-mouse2",url:"09/mouse2.png"},
            {containerId:"page10-order",url:"09/order.png"},
            {containerId:"page10-patient",url:"09/patient.png"},
            {containerId:"page10-title",url:"09/title.png"}
        ],
        page11:[
            {containerId:"page11-background",url:"10/background.png"},
            {containerId:"page11-nolight",url:"10/nolight.png"},
            {containerId:"page11-patient1",url:"10/patient1.png"},
            {containerId:"page11-patient2",url:"10/patient2.png"},
            {containerId:"page11-room",url:"10/room.png"},
            {containerId:"page11-tv-off",url:"10/tv-off.png"},
            {containerId:"page11-tv-on",url:"10/tv-on.png"},
            {containerId:"page11-tv-screen1",url:"10/tv-screen1.png"},
            {containerId:"page11-tv-screen2",url:"10/tv-screen2.png"},
            {containerId:"page11-vr-line",url:"10/vr-line.png"},
            {containerId:"page11-vr-watch",url:"10/vr-watch.png"},
            {containerId:"page11-title",url:"10/title.png"}
        ],
        page12:[
            {containerId:"page12-circle",url:"10-5/circle.png"},
            {containerId:"page12-line1",url:"10-5/line.png"},
            {containerId:"page12-line2",url:"10-5/line.png"},
            {containerId:"page12-line3",url:"10-5/line.png"},
            {containerId:"page12-service1-icon",url:"10-5/service1-icon.png"},
            {containerId:"page12-service1-name",url:"10-5/service1-name.png"},
            {containerId:"page12-service2-icon",url:"10-5/service2-icon.png"},
            {containerId:"page12-service2-name",url:"10-5/service2-name.png"},
            {containerId:"page12-service3-icon",url:"10-5/service3-icon.png"},
            {containerId:"page12-service3-name",url:"10-5/service3-name.png"},
            {containerId:"page12-service-title",url:"10-5/service-title.png"},
            {containerId:"page12-title-back",url:"10-5/title-back.png"}
        ],
        page13:[
            {containerId:"page13-circle-top",url:"11/circle-top.png"},
            {containerId:"page13-circle-bottom",url:"11/circle-bottom.png"},
            {containerId:"page13-line1-top",url:"11/line.png"},
            {containerId:"page13-line2-top",url:"11/line.png"},
            {containerId:"page13-line3-top",url:"11/line.png"},
            {containerId:"page13-line4-top",url:"11/line.png"},
            {containerId:"page13-line1-bottom",url:"11/line.png"},
            {containerId:"page13-line2-bottom",url:"11/line.png"},
            {containerId:"page13-line3-bottom",url:"11/line.png"},
            {containerId:"page13-line4-bottom",url:"11/line.png"},
            {containerId:"page13-service1-top",url:"11/service1-top.png"},
            {containerId:"page13-service1-bottom",url:"11/service1-bottom.png"},
            {containerId:"page13-service2-top",url:"11/service2-top.png"},
            {containerId:"page13-service2-bottom",url:"11/service2-bottom.png"},
            {containerId:"page13-service3-top",url:"11/service3-top.png"},
            {containerId:"page13-service3-bottom",url:"11/service3-bottom.png"},
            {containerId:"page13-service4-top",url:"11/service4-top.png"},
            {containerId:"page13-service4-bottom",url:"11/service4-bottom.png"},
            {containerId:"page13-title",url:"11/title.png"}
        ],
        page14:[
            {containerId:"page14-background",url:"12/background.png"},
            {containerId:"page14-introduce",url:"12/introduce.png"},
            {containerId:"page14-qrcode",url:"12/qrcode.png"},
            {containerId:"page14-arrow",url:"12/arrow.png"}
        ]
    },
    imgScenes:{
        page1:[
            ["car","logo","hospital","huiguTitle","serviceIntroduce","tree"]
            ,{add:["yun1"],addClass:[{id:"yun1",class:"page1-yun1-start"}],time:1000}
            ,{add:["yun2"],addClass:[{id:"yun2",class:"page1-yun2-start"}],time:5000}
            ,{add:["yun3"],addClass:[{id:"yun3",class:"page1-yun3-start"}],time:9000}
            ,{add:["yun4"],addClass:[{id:"yun4",class:"page1-yun4-start"}],time:13000}
        ],
        page2:[
            ["background","desk","doctor1","door-close","title"]
            ,{add:["door-open"],remove:["door-close"],time:1000}
            ,{add:["patient2"],remove:[],time:2000}
            ,{addClass:[{id:"patient2",class:"page2-patient2-in"}],time:2000}
            ,{add:["msg"],remove:[],time:6500}
            ,{addClass:[{id:"msg",class:"page2-msg2"}],removeClass:[],time:6500}
            ,{add:[],remove:["msg"],time:7500}
            ,{add:["doctor2"],remove:["doctor1"],time:8000}
            ,{add:["hand"],remove:[],time:9000}
            ,{time:11000}
        ],
        page3:[
            ["background","left-hand","phone-menu","pointer","title","phone-background"]
            ,{add:["right-hand"],remove:[],addClass:[{id:"right-hand",class:"page3-right-hand1"}],time:0}
            ,{add:["cover"],remove:[],time:1000}
            ,{add:["order","top-col"],remove:["right-hand"],removeClass:[{id:"right-hand",class:"page3-right-hand1"}],time:1500}
            ,{add:["cardid"],time:1750}
            ,{add:["name"],time:2000}
            ,{add:["phone-number"],time:2250}
            ,{add:["year"],time:2500}
            ,{add:["select-case1"],time:2750}
            ,{add:["time-space"],time:3000}
            ,{add:["right-hand"],addClass:[{id:"right-hand",class:"page3-right-hand2"}],time:3500}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand2-2"}],time:3500}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand3"}],time:4000}
            ,{add:["select-case2"],remove:["select-case1"],time:4000}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand4"}],time:5000}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand5"},{id:"order",class:"page3-order2"}],time:6000}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand6"}],time:7000}
            ,{add:["msg"],time:7000}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand7"}],time:7500}
            ,{addClass:[{id:"left-hand-container",class:"page3-left-hand-container2"}],time:8000}
            ,{addClass:[{id:"right-hand",class:"page3-right-hand8"}],time:8000}
            ,{addClass:[{id:"title",class:"page3-title2"}],time:8000}
            ,{time:8000}
        ],
        page4:[
            ["background-far","background-near","title","yun1","yun2"]
            ,{addClass:[{id:"container",class:"page4-container2"}],time:0}
            ,{add:["compute","desk","hand","mouse1","service"],addClass:[{id:"service-container",class:"page4-service-container2"}],time:1000}
            ,{add:["patient-msg"],addClass:[{id:"patient-msg",class:"page4-patient-msg2"}],time:2500}
            ,{add:["dialog","mouse2"],remove:["mouse1"],addClass:[{id:"dialog",class:"page4-dialog2"},{id:"hand",class:"page4-hand2"}],time:3500}
            ,{add:["mouse1"],remove:["dialog","mouse2"],time:4500}
            ,{time:7000}
        ],
        page5:[
            ["background","compute","hand","keybord","keybord-line","msg2","search","title"]
            ,{addClass:[{id:"hand",class:"page5-hand2"}],time:0}
            ,{add:["msg1"],addClass:[{id:"msg1",class:"page5-msg1-2"},{id:"msg2",class:"page5-msg2-2"},{id:"search",class:"page5-search2"}],time:2000}
            ,{remove:["search","msg2"],time:3000}
            ,{add:["doctor1"],addClass:[{id:"doctor1",class:"page5-doctor1-2"}],time:2500}
            ,{add:["doctor2"],addClass:[{id:"doctor2",class:"page5-doctor2-2"}],time:3000}
            ,{add:["doctor3"],addClass:[{id:"doctor3",class:"page5-doctor3-2"}],time:3500}
            ,{add:["background5","screen-border","screen-back"],remove:["background","compute","hand","keybord","keybord-line","title"],time:5000}
            ,{addClass:[{id:"compute-compute-container",class:"page5-compute-compute-container2"}],time:7000}
            ,{add:["shadow-back","shadow-line","hand5","doctor","disease-msg","background-title"],remove:["screen-border","screen-back","doctor1","doctor2","doctor3","msg1"],addClass:[{id:"shadow-container",class:"page5-shadow-container2"},{id:"background-title",class:"page5-background-title2"}],time:8000}
            ,{add:["light"],time:9000}
            ,{add:["title5"],time:9000}
            ,{add:["expert1"],addClass:[{id:"expert1",class:"page5-expert-in"}],time:9500}
            ,{add:["expert3"],addClass:[{id:"expert3",class:"page5-expert-in"}],time:10000}
            ,{add:["expert2"],addClass:[{id:"expert2",class:"page5-expert-in"}],time:10500}
            ,{add:["image"],addClass:[{id:"disease-msg",class:"page5-disease-msg-out"},{id:"image",class:"page5-image-in"}],time:14000}
            ,{addClass:[{id:"hand5",class:"page5-hand5-rotate"}],time:16000}
            ,{add:["expert2-phone"],time:17500}
            ,{remove:["expert1","expert2","expert3","light","image","title5","expert2-phone","background5","shadow-back","shadow-line","hand5","doctor","disease-msg","background-title"],time:18000}
        ],
        page6:[
            ["background","left-hand","left-hand-pointer","title","progress-bar"]
            ,{add:["progress-bar","image"],addClass:[{id:"image",class:"page6-image-in"}],time:0}
            ,{remove:["progress-bar"],time:1800}
            ,{add:["right-hand-close"],addClass:[{id:"right-hand-close",class:"page6-right-hand-close-in"}],time:2500}
            ,{add:["right-hand-open"],remove:["right-hand-close"],addClass:[{id:"image",class:"page6-image-big"}],time:3500}
            ,{add:["flag"],addClass:[{id:"flag",class:"page6-flag-in"}],time:5000}
            ,{add:["right-hand-click"],remove:["right-hand-open"],time:6000}
            ,{addClass:[{id:"right-hand-click",class:"page6-right-hand-click-move"}],time:7000}
            ,{addClass:[{id:"right-hand-click",class:"page6-right-hand-click-click"}],time:8000}
            ,{addClass:[{id:"right-hand-click",class:"page6-right-hand-click-out"}],time:9000}
            ,{add:["order"],remove:["right-hand-click"],addClass:[{id:"order",class:"page6-order-big-in"}],time:10000}
            ,{addClass:[{id:"left-hand-container",class:"page6-left-hand-container-out"},{id:"title",class:"page6-title-out"}],time:11000}
            ,{time:12500}
        ],
        page7:[
            []
            ,{add:["title-back","service-title"],addClass:[{id:"title-back",class:"page7-title-back-in"},{id:"service-title",class:"page7-service-title-in"}],time:0}
            ,{add:["circle"],addClass:[{id:"circle",class:"page7-circle-in"}],time:1000}
            ,{add:["line1"],addClass:[{id:"line1",class:"page7-line-in"}],time:1500}
            ,{add:["service1-icon"],addClass:[{id:"service1-icon",class:"page7-service-icon-in"}],time:2000}
            ,{add:["service1-name"],addClass:[{id:"service1-name",class:"page7-service-name-in"}],time:3000}
            ,{add:["line2"],addClass:[{id:"line2",class:"page7-line-in"}],time:3500}
            ,{add:["service2-icon"],addClass:[{id:"service2-icon",class:"page7-service-icon-in"}],time:4000}
            ,{add:["service2-name"],addClass:[{id:"service2-name",class:"page7-service-name-in"}],time:5000}
            ,{add:["line3"],addClass:[{id:"line3",class:"page7-line-in"}],time:5500}
            ,{add:["service3-icon"],addClass:[{id:"service3-icon",class:"page7-service-icon-in"}],time:6000}
            ,{add:["service3-name"],addClass:[{id:"service3-name",class:"page7-service-name-in"}],time:7000}
            ,{add:["line4"],addClass:[{id:"line4",class:"page7-line-in"}],time:7500}
            ,{add:["service4-icon"],addClass:[{id:"service4-icon",class:"page7-service-icon-in"}],time:8000}
            ,{add:["service4-name"],addClass:[{id:"service4-name",class:"page7-service-name-in"}],time:9000}
            ,{add:["line5"],addClass:[{id:"line5",class:"page7-line-in"}],time:9500}
            ,{add:["service5-icon"],addClass:[{id:"service5-icon",class:"page7-service-icon-in"}],time:10000}
            ,{add:["service5-name"],addClass:[{id:"service5-name",class:"page7-service-name-in"}],time:11000}
            ,{addClass:[{id:"title-back",class:"page7-title-back-out"},{id:"service-title",class:"page7-service-title-out"},{id:"service-list-container",class:"page7-service-list-container-out"}],time:12000}
            ,{time:13000}
        ],
        page8:[
            ["background","mountain"]
            ,{addClass:[{id:"container",class:"page8-container-in"}],time:0}
            ,{add:["airfly"],addClass:[{id:"airfly",class:"page8-airfly-in"}],time:1000}
            ,{addClass:[{id:"mountain",class:"page8-mountain-move"}],time:2000}
            ,{add:["gonglu","car"],addClass:[{id:"airfly",class:"page8-airfly-out"},{id:"car-container",class:"page8-car-container-in"}],time:4000}
            ,{remove:["mountain","airfly"],time:5000}
            ,{addClass:[{id:"car",class:"page8-car-move"}],time:5000}
            ,{add:["background8"],addClass:[{id:"container",class:"page8-container-out"},{id:"opera-container",class:"page8-opera-container-in"}],time:7000}
            ,{add:["expert","hand","light","doctor1","doctor2","opera-table","title"],addClass:[
                {id:"expert-container",class:"page8-expert-container-in"},
                {id:"doctor-container",class:"page8-doctor-container-in"},
                {id:"light",class:"page8-light-in"}
            ],time:9000}
            ,{addClass:[{id:"hand",class:"page8-hand-move"}],time:12000}
            ,{remove:["title"],addClass:[
                {id:"expert-container",class:"page8-expert-container-out"},
                {id:"doctor-container",class:"page8-doctor-container-out"},
                {id:"light",class:"page8-light-out"}
            ],time:14000}
            ,{remove:["background8"],time:16000}
        ],
        page9:[
            []
            ,{add:["title-back","service-title"],addClass:[{id:"title-back",class:"page9-title-back-in"},{id:"service-title",class:"page9-service-title-in"}],time:0}
            ,{add:["circle"],addClass:[{id:"circle",class:"page9-circle-in"}],time:1000}
            ,{add:["line1"],addClass:[{id:"line1",class:"page9-line-in"}],time:1500}
            ,{add:["service1-icon"],addClass:[{id:"service1-icon",class:"page9-service-icon-in"}],time:2000}
            ,{add:["service1-name"],addClass:[{id:"service1-name",class:"page9-service-name-in"}],time:2500}
            ,{add:["line2"],addClass:[{id:"line2",class:"page9-line-in"}],time:2500}
            ,{add:["service2-icon"],addClass:[{id:"service2-icon",class:"page9-service-icon-in"}],time:3000}
            ,{add:["service2-name"],addClass:[{id:"service2-name",class:"page9-service-name-in"}],time:3500}
            ,{add:["line3"],addClass:[{id:"line3",class:"page9-line-in"}],time:3500}
            ,{add:["service3-icon"],addClass:[{id:"service3-icon",class:"page9-service-icon-in"}],time:4000}
            ,{add:["service3-name"],addClass:[{id:"service3-name",class:"page9-service-name-in"}],time:4500}
            ,{add:["line4"],addClass:[{id:"line4",class:"page9-line-in"}],time:4500}
            ,{add:["service4-icon"],addClass:[{id:"service4-icon",class:"page9-service-icon-in"}],time:5000}
            ,{add:["service4-name"],addClass:[{id:"service4-name",class:"page9-service-name-in"}],time:6000}
            ,{add:["line5"],addClass:[{id:"line5",class:"page9-line-in"}],time:6500}
            ,{add:["service5-icon"],addClass:[{id:"service5-icon",class:"page9-service-icon-in"}],time:7000}
            ,{add:["service5-name"],addClass:[{id:"service5-name",class:"page9-service-name-in"}],time:7500}
            ,{addClass:[{id:"title-back",class:"page9-title-back-out"},{id:"service-title",class:"page9-service-title-out"},{id:"service-list-container",class:"page9-service-list-container-out"}],time:8000}
            ,{time:9000}
        ],
        page10:[
            []
            ,{add:["background","title"],addClass:[{id:"background",class:"page10-background-in"}],time:0}
            ,{add:["left-hand","left-hand-pointer","mouse1","patient"],addClass:[{id:"left-hand-container",class:"page10-left-hand-container-in"}],time:1000}
            ,{addClass:[{id:"patient",class:"page10-patient-in"},{id:"mouse1",class:"page10-mouse1-in"}],time:1500}
            ,{add:["dialog","mouse2"],remove:["mouse1"],addClass:[{id:"dialog",class:"page10-dialog-in"}],time:2000}
            ,{add:["mouse1"],remove:["mouse2"],time:3000}
            ,{remove:["dialog"],time:4000}
            ,{add:["order"],addClass:[{id:"order",class:"page10-order-big-in"}],time:5000}
            ,{addClass:[{id:"left-hand-container",class:"page10-left-hand-container-out"}],time:7000}
            ,{remove:["title"],addClass:[{id:"background",class:"page10-background-out"}],time:8000}
        ],
        page11:[
            ["background","nolight","room","title","tv-off"]
            ,{add:["tv-on"],addClass:[{id:"nolight",class:"page11-nolight-out"},{id:"tv-on",class:"page11-tv-on-in"}],time:0}
            ,{add:["tv-screen1"],addClass:[{id:"tv-screen1",class:"page11-tv-screen1-in"}],time:1000}
            ,{add:["patient1"],addClass:[{id:"patient1",class:"page11-patient1-in"}],time:2000}
            ,{add:["vr-watch","vr-line"],addClass:[{id:"vr-watch",class:"page11-vr-watch-in"},{id:"vr-line",class:"page11-vr-line-in"}],time:3000}
            ,{add:["tv-screen2","patient2"],remove:["tv-screen1","patient1"],time:4000}
            ,{add:["tv-screen1","patient1"],remove:["tv-screen2","patient2"],time:4500}
            ,{add:["tv-screen2","patient2"],remove:["tv-screen1","patient1"],time:5000}
            ,{add:["tv-screen1","patient1"],remove:["tv-screen2","patient2"],time:5500}
            ,{addClass:[{id:"container",class:"page11-container-out"}],time:6000}
            ,{time:7000}
        ],
        page12:[
            []
            ,{add:["title-back","service-title"],addClass:[{id:"title-back",class:"page12-title-back-in"},{id:"service-title",class:"page12-service-title-in"}],time:0}
            ,{add:["circle"],addClass:[{id:"circle",class:"page12-circle-in"}],time:1000}
            ,{add:["line1"],addClass:[{id:"line1",class:"page12-line-in"}],time:1500}
            ,{add:["service1-icon"],addClass:[{id:"service1-icon",class:"page12-service-icon-in"}],time:2000}
            ,{add:["service1-name"],addClass:[{id:"service1-name",class:"page12-service-name-in"}],time:2500}
            ,{add:["line2"],addClass:[{id:"line2",class:"page12-line-in"}],time:2500}
            ,{add:["service2-icon"],addClass:[{id:"service2-icon",class:"page12-service-icon-in"}],time:3000}
            ,{add:["service2-name"],addClass:[{id:"service2-name",class:"page12-service-name-in"}],time:3500}
            ,{add:["line3"],addClass:[{id:"line3",class:"page12-line-in"}],time:3500}
            ,{add:["service3-icon"],addClass:[{id:"service3-icon",class:"page12-service-icon-in"}],time:4000}
            ,{add:["service3-name"],addClass:[{id:"service3-name",class:"page12-service-name-in"}],time:4500}
            ,{addClass:[{id:"title-back",class:"page12-title-back-out"},{id:"service-title",class:"page12-service-title-out"},{id:"service-list-container",class:"page12-service-list-container-out"}],time:6000}
        ],
        page13:[
            []
            ,{add:["circle-top"],addClass:[{id:"circle-top",class:"page13-circle-top-in"}],time:0}
            ,{add:["line1-top"],addClass:[{id:"line1-top",class:"page13-line-top-in"}],time:500}
            ,{add:["service1-top"],addClass:[{id:"service1-top",class:"page13-service-top-in"}],time:1000}
            ,{add:["line2-top"],addClass:[{id:"line2-top",class:"page13-line-top-in"}],time:1500}
            ,{add:["service2-top"],addClass:[{id:"service2-top",class:"page13-service-top-in"}],time:2000}
            ,{add:["line3-top"],addClass:[{id:"line3-top",class:"page13-line-top-in"}],time:2500}
            ,{add:["service3-top"],addClass:[{id:"service3-top",class:"page13-service-top-in"}],time:3000}
            ,{add:["line4-top"],addClass:[{id:"line4-top",class:"page13-line-top-in"}],time:3500}
            ,{add:["service4-top"],addClass:[{id:"service4-top",class:"page13-service-top-in"}],time:4000}
            ,{add:["title"],addClass:[{id:"title",class:"page13-title-in"}],time:0}

            ,{add:["circle-bottom"],addClass:[{id:"circle-bottom",class:"page13-circle-bottom-in"}],time:0}
            ,{add:["line1-bottom"],addClass:[{id:"line1-bottom",class:"page13-line-bottom-in"}],time:500}
            ,{add:["service1-bottom"],addClass:[{id:"service1-bottom",class:"page13-service-bottom-in"}],time:1000}
            ,{add:["line2-bottom"],addClass:[{id:"line2-bottom",class:"page13-line-bottom-in"}],time:1500}
            ,{add:["service2-bottom"],addClass:[{id:"service2-bottom",class:"page13-service-bottom-in"}],time:2000}
            ,{add:["line3-bottom"],addClass:[{id:"line3-bottom",class:"page13-line-bottom-in"}],time:2500}
            ,{add:["service3-bottom"],addClass:[{id:"service3-bottom",class:"page13-service-bottom-in"}],time:3000}
            ,{add:["line4-bottom"],addClass:[{id:"line4-bottom",class:"page13-line-bottom-in"}],time:3500}
            ,{add:["service4-bottom"],addClass:[{id:"service4-bottom",class:"page13-service-bottom-in"}],time:4000}
            ,{addClass:[{id:"title",class:"page13-title-out"},{id:"circle-top-container",class:"page13-circle-top-container-out"},{id:"circle-bottom-container",class:"page13-circle-bottom-container-out"}],time:6000}
        ],
        page14:[
            ["background"]
            ,{addClass:[{id:"container",class:"page14-container-in"}],time:0}
            ,{add:["introduce"],addClass:[{id:"introduce",class:"page14-introduce-in"}],time:1000}
            ,{add:["arrow"],addClass:[{id:"arrow",class:"page14-arrow-float"}],time:2000}
        ]
    }
}